# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 13:33
from __future__ import unicode_literals

import Registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('academic_yearcode', models.CharField(blank=True, default=False, max_length=15, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'academic_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'academic_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=250)),
                ('is_active', models.CharField(max_length=1)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('class_code', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'class_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassSectionRelation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'class_section_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassSubjectRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'class_subject_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depatment_name', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'department_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParentsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('emai_id', models.CharField(max_length=250)),
                ('contact_num', models.CharField(max_length=250)),
                ('is_active', models.CharField(max_length=1)),
                ('created_date', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'parents_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=250)),
                ('school_address', models.CharField(max_length=250)),
                ('contact_num', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('logo', models.FileField(upload_to=Registration.models.content_file_name_school)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'school_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=250)),
                ('is_active', models.CharField(max_length=1)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('section_code', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'sections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('contact_num', models.CharField(max_length=250)),
                ('birth_date', models.DateField()),
                ('adress', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('is_active', models.CharField(max_length=1)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('identity_type', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'staff_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=45)),
                ('document_path', models.FileField(upload_to=Registration.models.content_file_name_doc)),
            ],
            options={
                'db_table': 'staff_document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentClassSubjectRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('class_id', models.IntegerField(blank=True, null=True)),
                ('subject_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_class_subject_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=250)),
                ('student_enrollment_num', models.CharField(max_length=250)),
                ('mother_name', models.CharField(max_length=250)),
                ('father_name', models.CharField(max_length=250)),
                ('adress', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('photo', models.FileField(upload_to=Registration.models.content_file_name)),
                ('is_active', models.CharField(max_length=1)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('middle_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('parent_mail', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'student_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('is_active', models.CharField(max_length=1)),
                ('type', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('code', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('email_id', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_details',
                'managed': False,
            },
        ),
    ]
